cmake_minimum_required(VERSION 3.20)
project(socom_retail_ui_v7 LANGUAGES CXX)
if(NOT WIN32)
  message(FATAL_ERROR "Windows target")
endif()
add_executable(socom_retail_ui WIN32 main.cpp)
target_compile_features(socom_retail_ui PRIVATE cxx_std_17)
target_compile_definitions(socom_retail_ui PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(socom_retail_ui PRIVATE shell32 gdiplus ole32)
if(MSVC)
  target_compile_options(socom_retail_ui PRIVATE /W4 /permissive-)
endif()

add_executable(socom_texture_tool socom_texture_tool.cpp)
target_compile_features(socom_texture_tool PRIVATE cxx_std_17)
if(MSVC)
  target_compile_options(socom_texture_tool PRIVATE /W4 /permissive-)
endif()
