#!/usr/bin/env python3
"""Build a dependency-free SOCOM Native runtime pack from the project's M8 glTF exports.

This tool intentionally consumes only files generated by the existing reverse-engineering
exporters. It does not embed or distribute original SOCOM data.

The resulting .snr file contains flattened render triangles and collision triangles in
meters. The first runtime milestone uses vertex color + simple lighting rather than
textures; UVs/textures stay in the source glTF and will be added to the runtime next.
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import struct
import sys
from dataclasses import dataclass
from typing import Iterable, Sequence

MAGIC = b"SOCOMR1\0"
VERSION = 1

COMPONENT_FORMAT = {
    5120: ("b", 1, True),   # BYTE
    5121: ("B", 1, False),  # UNSIGNED_BYTE
    5122: ("h", 2, True),   # SHORT
    5123: ("H", 2, False),  # UNSIGNED_SHORT
    5125: ("I", 4, False),  # UNSIGNED_INT
    5126: ("f", 4, True),   # FLOAT
}

TYPE_COMPONENTS = {
    "SCALAR": 1,
    "VEC2": 2,
    "VEC3": 3,
    "VEC4": 4,
    "MAT2": 4,
    "MAT3": 9,
    "MAT4": 16,
}


@dataclass
class RenderVertex:
    px: float
    py: float
    pz: float
    nx: float
    ny: float
    nz: float
    r: int
    g: int
    b: int
    a: int


@dataclass
class CollisionTriangle:
    a: tuple[float, float, float]
    b: tuple[float, float, float]
    c: tuple[float, float, float]
    n: tuple[float, float, float]
    material: int
    flags: int = 0


def clamp(v: float, lo: float, hi: float) -> float:
    return lo if v < lo else hi if v > hi else v


def vsub(a: Sequence[float], b: Sequence[float]) -> tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def vcross(a: Sequence[float], b: Sequence[float]) -> tuple[float, float, float]:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def vdot(a: Sequence[float], b: Sequence[float]) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def vlen(a: Sequence[float]) -> float:
    return math.sqrt(vdot(a, a))


def vnormalize(a: Sequence[float]) -> tuple[float, float, float]:
    length = vlen(a)
    if length <= 1e-12:
        return (0.0, 1.0, 0.0)
    inv = 1.0 / length
    return (a[0] * inv, a[1] * inv, a[2] * inv)


def mat_identity() -> list[float]:
    return [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0,
    ]


def mat_mul(a: Sequence[float], b: Sequence[float]) -> list[float]:
    # Column-major: result = a * b.
    out = [0.0] * 16
    for col in range(4):
        for row in range(4):
            out[col * 4 + row] = sum(
                a[k * 4 + row] * b[col * 4 + k] for k in range(4)
            )
    return out


def quat_matrix(q: Sequence[float]) -> list[float]:
    x, y, z, w = q
    n = math.sqrt(x * x + y * y + z * z + w * w)
    if n <= 1e-12:
        return mat_identity()
    x, y, z, w = x / n, y / n, z / n, w / n
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    return [
        1 - 2 * (yy + zz), 2 * (xy + wz),     2 * (xz - wy),     0.0,
        2 * (xy - wz),     1 - 2 * (xx + zz), 2 * (yz + wx),     0.0,
        2 * (xz + wy),     2 * (yz - wx),     1 - 2 * (xx + yy), 0.0,
        0.0,                0.0,                0.0,                1.0,
    ]


def node_matrix(node: dict) -> list[float]:
    if "matrix" in node:
        return [float(v) for v in node["matrix"]]

    t = node.get("translation", [0.0, 0.0, 0.0])
    r = node.get("rotation", [0.0, 0.0, 0.0, 1.0])
    s = node.get("scale", [1.0, 1.0, 1.0])

    tm = mat_identity()
    tm[12], tm[13], tm[14] = float(t[0]), float(t[1]), float(t[2])
    rm = quat_matrix(r)
    sm = mat_identity()
    sm[0], sm[5], sm[10] = float(s[0]), float(s[1]), float(s[2])
    return mat_mul(tm, mat_mul(rm, sm))


def transform_point(m: Sequence[float], p: Sequence[float]) -> tuple[float, float, float]:
    x, y, z = p
    return (
        m[0] * x + m[4] * y + m[8] * z + m[12],
        m[1] * x + m[5] * y + m[9] * z + m[13],
        m[2] * x + m[6] * y + m[10] * z + m[14],
    )


def inverse_transpose3(m: Sequence[float]) -> tuple[float, ...] | None:
    # Extract row-major 3x3 from column-major 4x4.
    a00, a01, a02 = m[0], m[4], m[8]
    a10, a11, a12 = m[1], m[5], m[9]
    a20, a21, a22 = m[2], m[6], m[10]

    c00 = a11 * a22 - a12 * a21
    c01 = a12 * a20 - a10 * a22
    c02 = a10 * a21 - a11 * a20
    c10 = a02 * a21 - a01 * a22
    c11 = a00 * a22 - a02 * a20
    c12 = a01 * a20 - a00 * a21
    c20 = a01 * a12 - a02 * a11
    c21 = a02 * a10 - a00 * a12
    c22 = a00 * a11 - a01 * a10
    det = a00 * c00 + a01 * c01 + a02 * c02
    if abs(det) <= 1e-12:
        return None
    inv_det = 1.0 / det

    # inverse(A), row-major
    inv = (
        c00 * inv_det, c10 * inv_det, c20 * inv_det,
        c01 * inv_det, c11 * inv_det, c21 * inv_det,
        c02 * inv_det, c12 * inv_det, c22 * inv_det,
    )
    # transpose(inverse(A)), row-major
    return (
        inv[0], inv[3], inv[6],
        inv[1], inv[4], inv[7],
        inv[2], inv[5], inv[8],
    )


def transform_normal(m: Sequence[float], n: Sequence[float]) -> tuple[float, float, float]:
    it = inverse_transpose3(m)
    if it is None:
        x, y, z = n
        return vnormalize((
            m[0] * x + m[4] * y + m[8] * z,
            m[1] * x + m[5] * y + m[9] * z,
            m[2] * x + m[6] * y + m[10] * z,
        ))
    x, y, z = n
    return vnormalize((
        it[0] * x + it[1] * y + it[2] * z,
        it[3] * x + it[4] * y + it[5] * z,
        it[6] * x + it[7] * y + it[8] * z,
    ))


class Gltf:
    def __init__(self, path: pathlib.Path):
        self.path = path
        with path.open("r", encoding="utf-8") as f:
            self.doc = json.load(f)
        self.buffers: list[bytes] = []
        for buf in self.doc.get("buffers", []):
            uri = buf.get("uri")
            if not uri or uri.startswith("data:"):
                raise RuntimeError("Only external binary glTF buffers are supported")
            data_path = (path.parent / uri).resolve()
            self.buffers.append(data_path.read_bytes())

    def accessor(self, index: int) -> list[tuple[float | int, ...]]:
        acc = self.doc["accessors"][index]
        if "bufferView" not in acc:
            raise RuntimeError("Sparse/bufferless accessors are not supported")
        view = self.doc["bufferViews"][acc["bufferView"]]
        comp_type = acc["componentType"]
        if comp_type not in COMPONENT_FORMAT:
            raise RuntimeError(f"Unsupported componentType {comp_type}")
        fmt_char, comp_size, signed_or_float = COMPONENT_FORMAT[comp_type]
        count = int(acc["count"])
        ncomp = TYPE_COMPONENTS[acc["type"]]
        elem_size = comp_size * ncomp
        stride = int(view.get("byteStride", elem_size))
        base = int(view.get("byteOffset", 0)) + int(acc.get("byteOffset", 0))
        data = self.buffers[int(view.get("buffer", 0))]
        normalized = bool(acc.get("normalized", False))
        fmt = "<" + fmt_char * ncomp

        out: list[tuple[float | int, ...]] = []
        for i in range(count):
            pos = base + i * stride
            values = struct.unpack_from(fmt, data, pos)
            if normalized and comp_type != 5126:
                if comp_type == 5121:
                    values = tuple(v / 255.0 for v in values)
                elif comp_type == 5123:
                    values = tuple(v / 65535.0 for v in values)
                elif comp_type == 5120:
                    values = tuple(max(-1.0, v / 127.0) for v in values)
                elif comp_type == 5122:
                    values = tuple(max(-1.0, v / 32767.0) for v in values)
            out.append(values)
        return out

    def world_nodes(self) -> Iterable[tuple[int, list[float]]]:
        scene_index = int(self.doc.get("scene", 0))
        roots = self.doc["scenes"][scene_index].get("nodes", [])

        def walk(index: int, parent: Sequence[float]):
            node = self.doc["nodes"][index]
            world = mat_mul(parent, node_matrix(node))
            yield index, world
            for child in node.get("children", []):
                yield from walk(int(child), world)

        identity = mat_identity()
        for root in roots:
            yield from walk(int(root), identity)


def material_fallback(material: int) -> tuple[int, int, int, int]:
    # Stable visible palette without requiring textures in milestone 1.
    x = (material + 1) * 0x9E3779B1
    r = 80 + ((x >> 0) & 0x7F)
    g = 80 + ((x >> 8) & 0x7F)
    b = 80 + ((x >> 16) & 0x7F)
    return (min(r, 255), min(g, 255), min(b, 255), 255)


def color_u8(value: Sequence[float | int] | None, material: int) -> tuple[int, int, int, int]:
    if value is None:
        return material_fallback(material)
    vals = list(value)
    if len(vals) == 3:
        vals.append(1.0)
    out = []
    for v in vals[:4]:
        fv = float(v)
        if fv <= 1.0001:
            fv *= 255.0
        out.append(int(round(clamp(fv, 0.0, 255.0))))
    while len(out) < 4:
        out.append(255)
    return tuple(out)  # type: ignore[return-value]


def extract_render(scene_path: pathlib.Path) -> tuple[list[RenderVertex], tuple[float, ...], dict]:
    gltf = Gltf(scene_path)
    vertices: list[RenderVertex] = []
    minp = [math.inf, math.inf, math.inf]
    maxp = [-math.inf, -math.inf, -math.inf]
    skipped_non_triangles = 0
    primitive_count = 0

    for node_index, world in gltf.world_nodes():
        node = gltf.doc["nodes"][node_index]
        if "mesh" not in node:
            continue
        mesh = gltf.doc["meshes"][int(node["mesh"])]
        for primitive in mesh.get("primitives", []):
            mode = int(primitive.get("mode", 4))
            if mode != 4:
                skipped_non_triangles += 1
                continue
            attrs = primitive["attributes"]
            positions = gltf.accessor(int(attrs["POSITION"]))
            normals = gltf.accessor(int(attrs["NORMAL"])) if "NORMAL" in attrs else None
            colors = gltf.accessor(int(attrs["COLOR_0"])) if "COLOR_0" in attrs else None
            if "indices" in primitive:
                idx = [int(v[0]) for v in gltf.accessor(int(primitive["indices"]))]
            else:
                idx = list(range(len(positions)))
            if len(idx) % 3:
                raise RuntimeError("Triangle primitive index count is not divisible by 3")
            material = int(primitive.get("material", 0))
            primitive_count += 1

            for source_index in idx:
                p = transform_point(world, positions[source_index])
                if normals is not None:
                    n = transform_normal(world, normals[source_index])
                else:
                    n = (0.0, 1.0, 0.0)
                c = color_u8(colors[source_index] if colors is not None else None, material)
                vertices.append(RenderVertex(*p, *n, *c))
                for axis in range(3):
                    minp[axis] = min(minp[axis], p[axis])
                    maxp[axis] = max(maxp[axis], p[axis])

    stats = {
        "render_primitives": primitive_count,
        "render_triangles": len(vertices) // 3,
        "render_vertices": len(vertices),
        "skipped_non_triangle_primitives": skipped_non_triangles,
    }
    return vertices, tuple(minp + maxp), stats


def extract_collision(collision_path: pathlib.Path) -> tuple[list[CollisionTriangle], tuple[float, ...], dict]:
    gltf = Gltf(collision_path)
    triangles: list[CollisionTriangle] = []
    minp = [math.inf, math.inf, math.inf]
    maxp = [-math.inf, -math.inf, -math.inf]
    skipped_degenerate = 0

    for node_index, world in gltf.world_nodes():
        node = gltf.doc["nodes"][node_index]
        if "mesh" not in node:
            continue
        mesh = gltf.doc["meshes"][int(node["mesh"])]
        for primitive in mesh.get("primitives", []):
            if int(primitive.get("mode", 4)) != 4:
                continue
            attrs = primitive["attributes"]
            positions = gltf.accessor(int(attrs["POSITION"]))
            if "indices" in primitive:
                idx = [int(v[0]) for v in gltf.accessor(int(primitive["indices"]))]
            else:
                idx = list(range(len(positions)))
            material = int(primitive.get("material", 0))
            for i in range(0, len(idx), 3):
                a = transform_point(world, positions[idx[i]])
                b = transform_point(world, positions[idx[i + 1]])
                c = transform_point(world, positions[idx[i + 2]])
                cross = vcross(vsub(b, a), vsub(c, a))
                area2 = vlen(cross)
                if area2 <= 1e-8:
                    skipped_degenerate += 1
                    continue
                n = vnormalize(cross)
                triangles.append(CollisionTriangle(a, b, c, n, material, 0))
                for p in (a, b, c):
                    for axis in range(3):
                        minp[axis] = min(minp[axis], p[axis])
                        maxp[axis] = max(maxp[axis], p[axis])

    stats = {
        "collision_triangles": len(triangles),
        "skipped_degenerate_collision_triangles": skipped_degenerate,
    }
    return triangles, tuple(minp + maxp), stats


def triangle_area(t: CollisionTriangle) -> float:
    return 0.5 * vlen(vcross(vsub(t.b, t.a), vsub(t.c, t.a)))


def choose_spawn(triangles: Sequence[CollisionTriangle], bounds: Sequence[float]) -> tuple[float, float, float]:
    if not triangles:
        raise RuntimeError("Cannot choose a spawn point without collision triangles")
    center_x = (bounds[0] + bounds[3]) * 0.5
    center_z = (bounds[2] + bounds[5]) * 0.5

    walkable = []
    for t in triangles:
        if t.n[1] < 0.70:
            continue
        area = triangle_area(t)
        if area < 0.15:
            continue
        cx = (t.a[0] + t.b[0] + t.c[0]) / 3.0
        cy = (t.a[1] + t.b[1] + t.c[1]) / 3.0
        cz = (t.a[2] + t.b[2] + t.c[2]) / 3.0
        walkable.append((cx, cy, cz, area, t))

    if not walkable:
        t = triangles[0]
        return (
            (t.a[0] + t.b[0] + t.c[0]) / 3.0,
            (t.a[1] + t.b[1] + t.c[1]) / 3.0 + 1.0,
            (t.a[2] + t.b[2] + t.c[2]) / 3.0,
        )

    ys = sorted(v[1] for v in walkable)
    median_y = ys[len(ys) // 2]
    low = ys[max(0, int(len(ys) * 0.10) - 1)]
    high = ys[min(len(ys) - 1, int(len(ys) * 0.70))]

    candidates = [v for v in walkable if low - 2.0 <= v[1] <= high + 2.0]
    if not candidates:
        candidates = walkable

    def score(v):
        cx, cy, cz, area, _ = v
        horizontal = math.hypot(cx - center_x, cz - center_z)
        vertical_penalty = abs(cy - median_y) * 3.0
        area_bonus = min(area, 25.0) * 0.15
        return horizontal + vertical_penalty - area_bonus

    best = min(candidates, key=score)
    return (best[0], best[1] + 1.05, best[2])


def write_pack(
    out_path: pathlib.Path,
    vertices: Sequence[RenderVertex],
    triangles: Sequence[CollisionTriangle],
    bounds: Sequence[float],
    spawn: Sequence[float],
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("wb") as f:
        f.write(MAGIC)
        f.write(struct.pack("<IIII", VERSION, len(vertices), len(triangles), 0))
        f.write(struct.pack("<6f", *bounds))
        f.write(struct.pack("<3f", *spawn))

        for v in vertices:
            f.write(struct.pack(
                "<6f4B",
                v.px, v.py, v.pz,
                v.nx, v.ny, v.nz,
                v.r, v.g, v.b, v.a,
            ))

        for t in triangles:
            f.write(struct.pack(
                "<12fII",
                *t.a, *t.b, *t.c, *t.n,
                t.material, t.flags,
            ))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scene", type=pathlib.Path, required=True,
                        help="m8_scene.gltf generated by socom_scene_gltf")
    parser.add_argument("--collision", type=pathlib.Path, required=True,
                        help="worldmodel_collision.gltf generated by socom_collision_gltf")
    parser.add_argument("--out", type=pathlib.Path, required=True,
                        help="output .snr runtime pack")
    parser.add_argument("--spawn", nargs=3, type=float, metavar=("X", "Y", "Z"),
                        help="override auto-selected spawn, in meters")
    parser.add_argument("--report", type=pathlib.Path,
                        help="optional JSON build report")
    args = parser.parse_args()

    if not args.scene.is_file():
        parser.error(f"scene not found: {args.scene}")
    if not args.collision.is_file():
        parser.error(f"collision not found: {args.collision}")

    print(f"[pack] Reading visual scene: {args.scene}")
    vertices, visual_bounds, visual_stats = extract_render(args.scene)
    print(f"[pack] Reading collision: {args.collision}")
    triangles, collision_bounds, collision_stats = extract_collision(args.collision)

    bounds = (
        min(visual_bounds[0], collision_bounds[0]),
        min(visual_bounds[1], collision_bounds[1]),
        min(visual_bounds[2], collision_bounds[2]),
        max(visual_bounds[3], collision_bounds[3]),
        max(visual_bounds[4], collision_bounds[4]),
        max(visual_bounds[5], collision_bounds[5]),
    )

    spawn = tuple(args.spawn) if args.spawn else choose_spawn(triangles, collision_bounds)
    write_pack(args.out, vertices, triangles, bounds, spawn)

    report = {
        "format": "SOCOMR1",
        "version": VERSION,
        **visual_stats,
        **collision_stats,
        "bounds_min_m": list(bounds[:3]),
        "bounds_max_m": list(bounds[3:]),
        "spawn_m": list(spawn),
        "output": str(args.out),
        "output_bytes": args.out.stat().st_size,
    }

    print(json.dumps(report, indent=2))
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
